version: 0.2

phases:
  install:
    commands:      
      - echo Installing source NPM
      - cd MFE/packages/marketing && npm install
  pre_build:
    commands:
      - echo Installing dependencies...     
  build:
    commands:
      - echo Build started...
      - npm run build
artifacts:
  base-directory: build
  files:    
      - "**/*"
