version: 0.2

phases:
  install:
    commands:      
      - echo Installing source NPM         
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started...
      - npm run build
artifacts:
  base-directory: build
  files:    
      - "**/*"
