version: 0.2

phases:
  install:
    commands:      
      - apt install -y npm
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm run start
  build:
    commands:
      - echo Building...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist
