version: 0.2

phases:
  install:
    commands:      
      - echo Installing source NPM 
      - npm install -y npm@latest      
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started...
      - npm build
artifacts:
  files:
    - "**/*"
  discard-paths: yes
  base-directory: $(echo ${CODEBUILD_INITIATOR} | cut -d'/' -f2)/dist
