version: 0.2
env:  
  variables:
    PRODUCTION_DOMAIN: "https://dqa4fqekzk0rd.cloudfront.net/"    
phases:
  install:
    commands:      
      - echo Installing source NPM
      - cd packages/container && npm install
  pre_build:
    commands:
      - echo Installing dependencies...     
  build:
    commands:
      - echo Build started...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: packages/container/dist
  
